stable L3 CI/CD pipeline

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -15,12 +15,15 @@ pipeline {
             }
         }
 
+        stage('Stop old container') {
+            steps {
+                sh 'docker rm -f mon-app || true'
+            }
+        }
+
         stage('Run Container') {
             steps {
-                sh '''
-                docker rm -f mon-app || true
-                docker run -d -p 5000:5000 --name mon-app mon-app
-                '''
+                sh 'docker run -d -p 5000:5000 --name mon-app mon-app'
             }
         }
 
@@ -28,6 +31,15 @@ pipeline {
             steps {
                 sh 'curl http://localhost:5000'
             }
+        }
+    }
+
+    post {
+        success {
+            echo 'PIPELINE SUCCESS 🚀'
+        }
+        failure {
+            echo 'PIPELINE FAILED ❌'
         }
     }
 }
